server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: gateway-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
